
	enum_start
	
	enum_elem THREAD2_DISABLED
	
	enum_elem THREAD2_LOADINGWALK
	enum_elem THREAD2_LOADINGWALKUP
	enum_elem THREAD2_LOADINGWALKDOWN
	enum_elem THREAD2_LOADINGWALKLEFT
	enum_elem THREAD2_LOADINGWALKRIGHT
	
	enum_elem THREAD2_AFTERLOADINGWALKUP
	enum_elem THREAD2_AFTERLOADINGWALKDOWN
	enum_elem THREAD2_AFTERLOADINGWALKLEFT
	enum_elem THREAD2_AFTERLOADINGWALKRIGHT
	
	enum_elem THREAD2_OPENDOOR
	enum_elem THREAD2_OPENDOORANIMATION
	
	
	enum_elem THREAD2_MAX